const data = [
  {
    id: 1,
    title: 'buttermilk',
    category: 'Breakfast',
    price: 15.99,
    img: 'https://www.simplyrecipes.com/thmb/bsHl85dfGja_VuQlhVpM7knVIIM=/2000x1334/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2006__05__Oatmeal-Pancakes-LEAD-1-355558f808104ae6adf48d88ac9e32cb.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'Lunch',
    price: 13.99,
    img: 'https://pyxis.nymag.com/v1/imgs/7f6/246/a2fa507ee9aafaadf0aef6e1932ed65223-30-grubstreet-takeout.rhorizontal.w700.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'Shakes',
    price: 6.99,
    img: 'https://sf1.mariefranceasia.com/wp-content/uploads/sites/7/2015/11/Robert-Timms-490x410.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'Breakfast',
    price: 20.99,
    img: 'https://irepo.primecp.com/2015/04/217062/Country-Bumpkin-Fried-Steak_Category-CategoryPageDefault_ID-954983.jpg?v=954983',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'Lunch',
    price: 22.99,
    img: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/how-to-fry-an-egg-vertical-1538168712.jpg?crop=1.00xw:0.376xh;0,0.347xh&resize=480:*',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'Desert',
    price: 18.99,
    img: 'https://loskitchenco.com/wp-content/uploads/2020/07/IMG_2722-scaled.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'Breakfast',
    price: 8.99,
    img: 'https://i.insider.com/5d36027c2516e972a2639a15?width=700',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'Lunch',
    price: 12.99,
    img: 'https://assets.sport.ro/assets/foodstory2019/2015/05/22/image_galleries/5942/cum-sa-gatesti-acasa-un-burger-ca-la-restaurant_size1.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'Shakes',
    price: 16.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ79bBjgpCD-uKaecp9LlGIZTD203sqb_Law&usqp=CAU',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default data;
